kind: pipeline
name: default

steps:
# - name: submodules
#   image: docker:git
#   environment:
#     SSH_KEY:
#       from_secret: ssh_key
#     SSH_HOST:
#       from_secret: ssh_host
#     USER_EMAIL:
#       from_secret: user_email
#     USER_NAME:
#       from_secret: user_name
#   commands:
#     # setup ssh for non https git pull
#     - ./building/drone-ssh-helper.sh submodule

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55.5
    buildDrafts: false
    buildFuture: false
    buildExpired: false
    url: https://karlredman.github.io
    output: ./site
    config: config.toml
    # minify: <not implemented>
    validate: true
  commands:
    # hmmm, it seems that our build specs break the plugin
    - hugo --gc --baseURL="https://karlredman.github.io/Articles" --config="config.toml" -d site

# - name: deploy
#   image: docker:git
#   environment:
#     SSH_KEY:
#       from_secret: ssh_key
#     SSH_HOST:
#       from_secret: ssh_host
#     USER_EMAIL:
#       from_secret: user_email
#     USER_NAME:
#       from_secret: user_name
#   commands:
#     - ./building/drone-ssh-helper.sh commit
