baseurl = "/"
title = "Articles"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "amnix"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
#
pygmentsCodeFences = true
# pygmentsStyle = "monokailight"
footnotereturnlinkcontents = "↩"
metaDataFormat = "yaml"


[Params]
  owner = "Karl N. Redman"
  pagefeatured = false
  home_title = "Karl N. Redman: "
  home_url = "https://karlredman.github.io"
#
  description = "Articles written by Karl N. Redman" # Site description. Used in meta description
  opengraph = true # Enable OpenGraph
  twitterCards = true # Enable Twitter Cards
  homeLayout = "2 columns + sidebar" # Configure home page layout
  listLayout = "2 columns + sidebar" # Configure layout for list pages
  singleLayout = "content + sidebar" # Configure layout for single pages
  mainSections = ["dev.to","medium","joplin","_resources"] # Set main page sections
  dateFormat = "January 02, 2006" # Change the format of dates
  customCSS = ["css/custom.css"] # Include custom CSS files
  comments = true # Enable comments for all site pages
  related = true # Enable Related Content (See https://gohugo.io/content-management/related/)
  mathjax = true # Enable MathJax for all site pages
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path. Optional
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional

[Params.Social] # Site Social block
  email = "karl.redman@gmail.com"
  # facebook = "karlredman"
  twitter = "Karl_Redman"
  # telegram = "username"
  # instagram = "username"
  # pinterest = "username"
  # vk = "username"
  linkedin = "karl-n-redman-850413"
  github = "karlredman"
  gitlab = "karl.redman"
  stackoverflow = "1725771"
  # mastodon = "username"
  medium = "karl.redman"

[Params.Widgets]
  recent = false # Enable "Recent Posts" widget
  recentNum = 5 # Set number of articles in the "Recent articles" widget
  recentDate = true # Show datetime in the "Recent Posts" widget
  categories = true # Enable "Categories" widget
  tags = true # Enable "Tags" widget
  tagsCounter = true # Enable counter for each tag in the "Tags" widget

[Params.Share] # Post Share block
  facebook = true
  twitter = true
  reddit = true
  telegram = true
  linkedin = true
  vk = true
  pocket = true

[Params.Manifest] # Web App Manifest config
  name = "Karl N. Redman Articles"
  shortName = "Karl N. Redman Articles"
  display = "standalone"
  backgroundColor = "#33333a"
  themeColor = "#5b5b67"
  description = "Articles written by Karl N. Redman"
  orientation = "portrait"
  startUrl = "/"
  scope = "/"

[outputFormats]
  [outputFormats.MANIFEST] # Add custom MANIFEST output format
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"] # Include MANIFEST format to home page
