@startuml
left to right direction
title Private Network + Traefik + Keycloak + Gatekeeper Overview

rectangle "Infrastructure" {

	package "Services" {

		package "Bare Metal" {
			component Dnsmasq
			database Mysql_service

			rectangle "Applications" {
				component Gitea
			}
		}

		package "Docker" {
			package "Routing" {
				component Traefik
				component Nginx
				component KeyCloak
				component KeyCloak_Proxy
			}

			package "Applicatons" {
				component Minio
				component NextCloud
				component Drone
				component Jenkins
				component whoami
				component "Static Site" as Hugo
			}
		}
	}

	package "Domain Namespace" {
		interface hostname.home as scuar_home
		interface hostname.dockernet as scuar_dockernet
		interface "hostname.lan /\nexample.com" as scuar_lan
	}
}

scuar_dockernet -[#Red]- Dnsmasq: IP 172.xxx.0.1
scuar_home -[#Red]- Dnsmasq: IP 10.127.127.1
scuar_lan -[#Red]- Dnsmasq: IP 127.0.0.1\n or xxx.xxx.xxx

Dnsmasq -[#Black]- Gitea: resolved
Dnsmasq -[#Black]- Traefik: resolved

Traefik -[bold,#Blue]- NextCloud: routed
Traefik -[bold,#Blue]- Drone: routed
Traefik -[bold,#Blue]- Gitea: routed

Traefik -[bold,#Blue]- KeyCloak: routed

KeyCloak -[bold,#Blue]- KeyCloak_Proxy: routed
KeyCloak_Proxy -[bold,#Blue]- Nginx: routed

KeyCloak -[bold,#Blue]- Jenkins: routed
KeyCloak -[bold,#Blue]- Minio: routed

Hugo -[bold,#Violet]- Nginx: routed
KeyCloak_Proxy -[bold,#Violet]- whoami: routed

scuar_dockernet .[#Black,dotted,thickness=2]. Traefik: docker network
scuar_home .[#Black,dotted,thickness=2]. Gitea: private network
scuar_home .[#Black,dotted,thickness=2]. Mysql_service: private network

cloud "Internet /\nExternalnNetwork /\nExternal DNS" as Internet
Internet .[#MidnightBlue]. scuar_lan: "Resolve URI Request\n(hostname.lan)"

@enduml


