@startmindmap
title Keycloak UI v5.0.0

* Keycloak Realm

** Realm Settings

*** General
****_ Name*
****_ Display name
****_ HTML Display name
****_ Enabled
*****_ [toggle]
****_ User-Managed Access
*****_ [toggle]
****_ Endpoints

*** Login
****_ User Registration
*****_ [toggle]
****_ Email as username
*****_ [toggle]
****_ Forgot password
*****_ [toggle]
****_ Remember Me
*****_ [toggle]
****_ Verify email
*****_ [toggle]
****_ Login with email
*****_ [toggle]
****_ Require SSL
*****_ [choice]
******_ all requests
******_ external requests
******_ none

*** Keys
****_ Active
****_ Passive
****_ Disabled
****_ Providers

*** Email
****_ Host*
****_ Port
****_ From Display Name
****_ From*
****_ Reply To Display Name
****_ Reply To
****_ Envelope From
****_ Enable SSL
*****_ [toggle]
****_ EnableTLS
*****_ [toggle]
****_ Enable Authentication
*****_ [toggle]

*** Themes
****_ Login Theme
*****_ [user defined choice]
****_ Account Theme
*****_ [user defined choice]
****_ Admin Console Theme
*****_ [user defined choice]
****_ Email Theme
*****_ [user defined choice]
****_ Internationalization Enabled
*****_ [toggle]

*** Cache
****_ Realm Cache
*****_ clear
******_ [button]
****_ User Cache
*****_ clear
******_ [button]
****_ Keys Cache
*****_ clear
******_ [button]

*** tokens
****_ Default Signature Algorithm
*****_ [choice]
****_ Revoke Refresh Token
*****_ [toggle]
****_ SSO Session Idle
****_ SSO Session Max
****_ SSO Session Idle Remember Me
****_ SSO Session Max Remember Me
****_ Offline Session Idle
****_ Offline Session Max Limited
*****_ [toggle]
****_ Access Token Lifespan
****_ Access Token Lifespan for Implicit Flow
****_ Client Login timeout
****_ Login timeout
****_ Login action timeout
****_ User-Initiated Action Lifespan
****_ Default Admin-Initiated Action Lifespan
****_ Override User-Initiated Action Lifespan

*** Client Regristration
**** Initial Access Tokens
**** Client Registration Policies
*****_ Anonymous Access Policies
*****_ Authenticated Access Policies

*** Security Defenses
**** Headers
*****_ X-Frame-Options
*****_ Content-Security-Policy
*****_ Content-Security-Policy-Report-Only
*****_ X-Conent-Type-Options
*****_ X-Robots-Tag
*****_ X-XSS-Protection
*****_ HTTP Strict Transport Security (HSTS)
**** Brute Force Detection
*****_ Enabled
******_ [toggle]


' ################### Clients

left side

** Clients

*** Client

**** Settings
*****_ Client ID
*****_ Name
*****_ Description
*****_ Enabled
*****_ Consent Required
*****_ Login Theme
*****_ Client Protocol
*****_ Access Type
*****_ Standard Flow Enabled
*****_ Implicit Flow Enabled
*****_ Direct Access Grants Enabled
*****_ Authorization Enabled
*****_ Root URL
*****_ Admin URL
*****_ Web Origins


***** Fine Grain OpenID Connect Configuration
******_ Access Token Signature Algorithm
******_ ID Token Signature Algorithm
******_ User Info Signed Response Algorithm
******_ Request Object Signature Algorithm
******_ Request Object Required


***** Advanced Settings
******_ Access Token Lifespan
******_ Oauth 2.0 Mutual TLS Certificate \nBound Access Tokens Enabled

***** Authentication Flow Overrides
******_ Browser Flow
******_ Direct Grant Flow

**** Credentials
*****_ Client Authenticator
*****_ Secret
******_ Regenerate Secret
*******_ [button]
*****_ Registration access tokens
******_ Regenerate registration access token
*******_ [button]

**** Roles
**** Client Scopes
**** Mappers
**** Scope
**** Revocation
**** Sessions
**** Offline Access
**** Clustering
**** Installation

' ################### Client Scopes

right side

** Client Scopes
*** Client Scopes
**** Client Scope

***** Settings
******_ Name*
******_ Description
******_ Protocol
******_ Display Consent Screen
*******_ [toggle]
******_ Consent Screen Text
******_ Include In Token Scope
*******_ [toggle]
******_ GUI order

***** Mappers
****** Map
*******_ Protocol
*******_ ID
*******_ Name
*******_ Mapper Type
*******_ Included Client Audience
*******_ Included Custom Audience
*******_ Add to ID token
********_ [toggle]
*******_ Add to access token
********_ [toggle]

***** Scope

*** Default Client Scopes

' ################### Roles

left side

** Roles

*** Realm Roles
**** Realm Role
***** Details
***** Attributes
***** Users in Role

*** Default Roles

left side

' #################### IDP / User Fed. / Auth

** Identity Providers
** User Federation
** Authentication

right side

' ################### Users

** Users
*** User

**** Details
*****_ ID
******_ [uneditable]
*****_ Created At
******_ [uneditable]
*****_ Email
*****_ First Name
*****_ Last Name
*****_ User Enabled
******_ [toggle]
*****_ Email Verified
******_ [toggle]
*****_ Required User Actions
*****_ Impersonate user
*****_ [button]

**** Attributes
***** Attribute
******_ Key
******_ Value

**** Credentials

***** Managed Password
******_ New Password
******_ Password Confirmation
******_ Temporary
*******_ [toggle]
******_ Reset Password
*******_ [button]

***** Disable Credentials
******_ Disable Types
******_ Disable Credential Types

***** Credential Reset
******_ Reset Actions
******_ Expires in
******_ Reset Actions Email
*******_ Send email
*******_ [button]

**** Role Mappings
**** Groups
**** Consents
**** Sessions

left side

' ################### Groups

** Groups
*** Group

**** Settings
*****_ Name*
**** Attributes
***** Attribute
******_ Key
******_ Value
**** Role Mappings
**** Members

@endmindmap
